include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_declare_return_types
    - always_put_required_named_parameters_first
    - avoid_as
    - avoid_bool_literals_in_conditional_expressions
    - avoid_empty_else
    - avoid_redundant_argument_values
    - combinators_ordering
    - comment_references
    - prefer_relative_imports
    - prefer_single_quotes